# Generated by Django 6.0.1 on 2026-08-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomembresia',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, help_text='Duración en días'),
        ),
    ]
