# Generated by Django 6.0.1 on 2026-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
